### ISSUE TITLE
wip: error handling for network conditions

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-pegasus#63]
**Tasks:**

- [ ] Create a custom error screen for when the user is not connected to the internet.
- [ ] Add a check in app initialization and show error screen if required
- [ ] Watch for change in network status and show error screen when required

**Additional Context**
- https://pub.dev/packages/connectivity_plus
- https://stackoverflow.com/questions/49648022/check-whether-there-is-an-internet-connection-available-on-flutter-app
