### ISSUE TITLE
wip: dark mode switch with state management

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-pegasus#64]
**Tasks:**

- [ ] Create a switch for dark mode in the more page
- [ ] Modify app config to allow for updates and to notify
- [ ] Store user's mode choice in shared_preferences
