### ISSUE TITLE
wip: optimize image loading

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-pegasus#67]
**Tasks:**

- [ ] Implement blurhash to display dummy images
- [ ] Download low quality image variants from imagekit for thumbnails
- [ ] Implement cached network image to prevent same image being downloaded multiple times
